### ISSUE TITLE
Modify inital tab data to have only desirable fields.  Create controlled vocabulary for proposal terms

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/llm4isi#5]

**Comment by mikedarcy** [comment]
Does this mean you want to import only a subset of the data fields in the spreadsheet, or do you want to import all of the data and only make visible specific fields?

**Comment by carlkesselman** [comment]
Not sure…. one approch would be a ELT methodology where we store the CSV as an asset, then import the whole thing, then remove columns.

Another approch would be to have the raw CSV as an asset, build a pipeline or notebook that trims out the columns we don’t want, and then uploads the result.  We could manage this using the workflow tables.

What do you think best.  Perhaps approch 2?

Carl

----------------------------------------------------------
Dr. Carl Kesselman
William H. Keck Professor of Engineering
Professor, Epstein Department of Industrial and Systems Engineering
Director Informatics Systems Research Division, Information Sciences Institute
Viterbi School of Engineering

Professor, Department of Population and Public Health Sciences, Keck School of Medicine
Professor, Biomedical Sciences, Ostrow School of Dentistry

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  ***@***.***
Web: http://www.isi.edu/~carl
















On Jun 26, 2024, at 9:25 AM, mikedarcy ***@***.***> wrote:



Does this mean you want to import only a subset of the data fields in the spreadsheet, or do you want to import all of the data and only make visible specific fields?

**Comment by mikedarcy** [comment]
I figured it would be better to have all of this data in the database and just not display it all. That way the data is there if for some reason we want to display more based on row-based ACLs. If there are fundamental privacy concerns and we don't actually _need_ the extra data, then perhaps it is best to import only the subset of fields we need to actually perform experiments.

As far as the process is concerned, since this is a one-time table load, I was simply going to script it with `deriva-py`.
